Added interfaces and traits
Network-Rail-Business-Systems/activity-log pull request #23
Opened 2024-12-03 14:15 UTC by Tahmid11

I have added in the trait and interface folders and some of the files.

2024-12-03 14:16 UTC, calum-gray commented on src/Interfaces/Actioned.php
> +}
blank line at end of file

2024-12-03 14:17 UTC, calum-gray commented on src/Traits/HasActions.php
> +}
blank line at end of file

2024-12-03 14:17 UTC, calum-gray commented on src/Traits/HasActivities.php
> +}
blank line at end of file

2024-12-03 14:21 UTC, calum-gray requested changes
could you add the activitylog interface too pls

2024-12-03 16:20 UTC, calum-gray requested changes
need to add the functions into user.php, see the example branch

2024-12-03 17:11 UTC, Tahmid11 commented
> need to add the functions into user.php, see the example branch

Thank you for catching that!

2024-12-04 08:03 UTC, AnthonyEdmonds commented on src/Traits/HasActions.php
> +        ) ->showSubject();
No space between function brace and arrow

2024-12-04 08:04 UTC, AnthonyEdmonds commented on tests/Models/User.php
> +        return route ('users.index', $this);
No space between function name and opening brace.

2024-12-04 08:04 UTC, AnthonyEdmonds reviewed
I hope you understand all of this, as you'll have to write tests for it soon!

2024-12-04 13:46 UTC, calum-gray approved these changes

2024-12-04 13:49 UTC, merged